export const styles = {
  header: {
    width: '100%',
    height: '64px',
    backgroundColor: 'transparent',
    color: 'white',
    display: 'flex',
    alignItems: 'center',
    paddingLeft: '24px',
    boxSizing: 'border-box',
    zIndex: 1100,
    boxShadow: 'none',
  },
  wrap: {
    display: 'flex',
    flexDirection: 'column',
    height: '100vh',            
    width: '100vw', 
    overflow: 'hidden',
    backgroundColor: 'whitesmoke',
    margin: 0,
    padding: 0,
  },
  content: {
    flexGrow: 1,
    boxSizing: 'border-box',
    width: '100%',
    height: '100%',
    overflow: 'hidden',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 0,
    margin: 0,
  },
  footer: {
    width: '100%',
    height: '60px',
    backgroundColor: '#1976d2',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    bottom: 0,
    color: 'white',
    marginTop: 'auto',
  },
};
